// Getters
export const IS_COLLAPSE = 'IS_COLLAPSE';
export const IS_LOGIN_DIALOG_VISIBLE = 'IS_LOGIN_DIALOG_VISIVLE';

// Mutations
export const MODIFY_IS_COLLAPSE = 'MODIFY_IS_COLLAPSE';
export const MODIFY_IS_LOGIN_DIALOG_VISIBLE = 'MODIFY_IS_LOGIN_DIALOG_VISIBLE';
export const TOGGLE_COLLAPSE = 'TOGGLE_COLLAPSE';
