stages:
  - lint
  - test

before_script:
  - node -v
  - npm -v
  - npm install -g yarn
  - yarn install

lint:
  stage: lint
  script:
    - yarn run lint

unit:
  stage: test
  script:
    - yarn run test:unit
