stages:
  - lint
  - test
  - build

before_script:
  - node -v
  - npm -v
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

unit:
  stage: test
  script:
    - npm run test:unit

build:
  stage: build
  script:
    - npm run build
