swagger: "2.0"
info:
  $ref: './info.yaml'

basePath: /mock

consumes:
  - application/json
produces:
  - application/json

definitions:
  $ref: './definitions.yaml#/definitions'

parameters:
  $ref: './parameters.yaml#/parameters'

paths:
  $ref: './paths.yaml#/paths'
